kiva/aries-guardianship-agency

README.md
src/config/env.json
src/manager/docker.service.ts

Updates to the latest aca-py image

Update aca-py image

---

src/manager/agent.manager.service.ts
src/manager/docker.service.ts

Automatically issue connection request on agent startup

---

src/manager/docker.service.ts

Updates to support our verifier flow

---

README.md
docker/Dockerfile
docker/Dockerfile.production
package-lock.json
package.json
src/agency/agency.controller.ts
src/app/app.controller.ts
src/app/app.module.ts
src/app/app.service.ts
src/controller/agent.controller.controller.ts
src/controller/agent.controller.service.ts
src/controller/agent.governance.ts
src/main.ts
src/manager/agent.manager.service.ts
src/router/agent.router.service.ts

updates to use public protocol-common package

---

src/manager/agent.manager.service.ts

Added some handling for if the container is already running (so it docker doesn't try to start it and fail). Also noticed that ttl is in seconds not ms so we should add 1.

Support already running containers

---

.circleci/config.yml
package.json
test/agents.e2e-spec.ts
test/smoke.e2e-spec.ts

Adds necessary change to get circleci support for this repo.  There are some todos left, which will have to addressed later.
1. most of the testing is heavily dependent on running services.  we need to change our tests to be more isolated.
2. still want the integration tests to run at some point

Circleci project setup

---

.circleci/config.yml

corrects docker file location

---

.circleci/config.yml
docker-compose.ci.yml
src/controller/agent.controller.module.ts
src/controller/agent.controller.service.ts
src/controller/agent.governance.factory.ts

1. creates factory and updates nest js to support injecting Agent Governance policy handler
2. fixes local vs ci builds by making ci use its own docker image

Gets DI working for Agent Governance Policy

---

resources/init.sql
src/controller/handler/issue.credential.ts

fix linting issues

---

.circleci/config.yml
docker-compose.ci.yml
docker-compose.yml
src/manager/docker.service.ts
test/connections.policies.e2e-spec.ts
test/credential.policies.e2e-spec.ts

get things set up

---

.circleci/config.yml
README.md

cleaning up CI file

---

docker-compose.ci.yml
docker-compose.yml
src/config/env.json

docker: align service and repo names

---

src/manager/k8s.service.ts

k8s: read namespace file sync

---

src/manager/k8s.service.ts

k8s: make it easier to manage agent services

---

.circleci/config.yml
test/connections.policies.e2e-spec.ts
test/credential.policies.e2e-spec.ts

updates tests to run in  aries-guardianship-agency container

---

src/app/global.cache.module.ts
src/config/env.json
src/manager/k8s.service.ts

make the default cache last one year

---

package.json
src/config/env.json
src/manager/agent.manager.service.ts
src/manager/docker.service.ts
src/router/agent.router.service.ts

Removes random ports for agents

---

.circleci/config.yml

adds linter to CI builds

---

dummy.env

add notes to dummy.env

---

src/controller/agent.controller.service.ts
src/controller/handler/connections.ts
src/controller/handler/issue.credential.ts
src/manager/agent.manager.service.ts
test/connections.policies.e2e-spec.ts
test/credential.policies.e2e-spec.ts

removes some of the http port cache data as its no longer needed.

---

src/manager/k8s.service.ts

k8s: deploy agent pods to hot standby node pool

---

src/manager/agent.manager.controller.ts
src/manager/agent.manager.service.ts

add separate endpoint to create connection

---

src/manager/agent.manager.service.ts
test/cache.behaviors.e2e-spec.ts
test/connections.policies.e2e-spec.ts
test/credential.policies.e2e-spec.ts

Adds more robust handling of startAgent

---

.circleci/config.yml
docker/Dockerfile.production

dockerfile: upgrade to Node 12

---

.circleci/config.yml

circleci: wait for integration tests before deploying from tag

---

.circleci/config.yml
docker/Dockerfile.production

This reverts commit f904f71758020b5c1984301e8ce5693999a5f55a, reversing
changes made to bd3ceb808817425494817fd433db890c5bda9f42.

Revert "Merge pull request #68 from kiva/upgrade-node"

---

src/manager/k8s.service.ts

k8s: tag logs with env in datadog

---

README.md
src/manager/agent.config.ts
src/manager/agent.manager.controller.ts
src/manager/agent.manager.service.ts
src/manager/docker.service.ts
src/manager/k8s.service.ts
test/cache.behaviors.e2e-spec.ts
test/connections.policies.e2e-spec.ts
test/credential.policies.e2e-spec.ts

replace alias with agentId, containerId and label

---

.circleci/config.yml

ci: potential fix for build issue

---

src/config/env.json

increase retry to 30s

---

src/controller/agent.controller.controller.ts
src/controller/agent.controller.service.ts
src/controller/handler/handlers.factory.ts
src/manager/agent.manager.service.ts

Cleaning up logs

---

docker-compose.ci.yml
docker-compose.yml

Add priviledged access to docker compose

---

README.md
docker-compose.yml
src/manager/agent.manager.service.ts

updates to clean up read me, postgres fix for windows operation

---

README.md
package-lock.json
package.json
src/controller/agent.controller.service.ts
src/manager/agent.config.ts
src/manager/agent.manager.controller.ts
src/manager/agent.manager.service.ts
src/manager/docker.service.ts

Adds ability to dynamically expose admin port for local environments.

---

package.json
src/controller/handler/handlers.factory.ts
src/controller/handler/problem.report.ts

adding problem report webhook handler

---

src/config/env.json
src/manager/agent.config.ts
src/manager/docker.service.ts
src/manager/k8s.service.ts

Improving AgentConfig and logging

---

package-lock.json
package.json

upgrade protocol-common to 0.1.20

---

src/config/governence.json
src/controller/handler/proof.ts
src/manager/agent.config.ts

Remove auto respond flag '--auto-respond-presentation-request' and updates proofs handler to complete the process successfully.

Remove auto respond flag --auto-respond-presentation-request

---

src/controller/handler/proof.ts
src/manager/agent.manager.service.ts

add exception handler on agent shutdown

---

src/config/governence.json
src/controller/agent.controller.service.ts
src/controller/handler/connections.ts
src/controller/handler/handlers.factory.ts
src/controller/handler/issue.credential.ts
src/controller/handler/proof.ts
src/manager/agent.config.ts
test/credential.policies.e2e-spec.ts

removes --auto-respond-credential-offer and adds governance

removes --auto-respond-credential-offer and adds governance

---

src/manager/agent.config.ts
test/connections.policies.e2e-spec.ts

removes --auto-respond-messages, updates test to prove states

---

package-lock.json
package.json
test/credential.policies.e2e-spec.ts

update aries-controller and add more tests

---

package-lock.json
package.json

bumps package version

---

src/manager/agent.config.ts
src/manager/agent.manager.controller.ts
src/manager/agent.manager.service.ts
test/cache.behaviors.e2e-spec.ts

adds code to allow tails server flags

---

src/manager/agent.config.ts
src/manager/agent.manager.service.ts
src/manager/docker.service.ts
src/manager/dtos/agent.create.dto.ts
src/manager/k8s.service.ts

make ports numbers

---

test/credential.policies.e2e-spec.ts

remove cred_def_id and see if things still work

---

.circleci/config.yml
README.md
src/config/env.json
test/cache.behaviors.e2e-spec.ts

changes version of aca-py to 5.6

---

dummy.env
test/credential.policies.e2e-spec.ts
test/credential.revocation.e2e-spec.ts

get base tests in

---

docker/indy-pool.dockerfile

upgrades local indy-pool for dev and testing

---

.circleci/config.yml

removes extra build step, combining tests into same step

---

.circleci/config.yml
docker-compose.ci.yml
docker-compose.yml
dummy.env
src/multitenant/mulittenant.service.ts
test/multitenant.connections.e2e-spec.ts
test/multitenant.credential.e2e-spec.ts

move multitenant startup args to envs

---

docker-compose.yml
src/config/env.json
src/multitenant/mulittenant.service.ts
test/multitenant.cache.e2e-spec.ts
test/multitenant.connections.e2e-spec.ts
test/multitenant.credential.e2e-spec.ts

handle cache misses

---

src/multitenant/mulittenant.service.ts

Bug details here: https://kiva.atlassian.net/browse/PRO-2896

Update regex to handle more error messages

---

package-lock.json
package.json
src/app/app.module.ts
src/controller/agent.controller.service.ts
src/transactions/transaction.controller.ts
src/transactions/transaction.module.ts
src/transactions/transaction.service.ts

Updates guardianship to receive basic messages

---

package-lock.json
package.json
src/manager/agent.manager.controller.ts
src/multitenant/multitenant.controller.ts

update protocol common

---

src/transactions/transaction.controller.ts
test/multitenant.credential.e2e-spec.ts

fixes api end point

---

package-lock.json
package.json
src/app/app.service.ts
src/transactions/transaction.module.ts

update app service

---

src/transactions/transaction.service.ts

cleanup from previous commits

---

src/transactions/persistence/data.service.ts
src/transactions/transaction.service.ts

fixes bug where all transactions are retrieved

---

package.json

change version of aries controller

---

package-lock.json
package.json

updates package version

---

package.json

bump version of controller

---

package-lock.json
package.json
test/credential.revocation.e2e-spec.ts

update test to check before and after

---

.circleci/config.yml

Resolves #156 
Signed-off-by: Jeff Kennedy <jeffk@kiva.org>

Circle CI should run protocol-integration-tests

---

src/ormconfig.ts

Signed-off-by: Jeff Kennedy <jeffk@kiva.org>

Update typeorm connection options to only look for javascript entities.

---

src/transactions/transaction.service.ts

fixing getting data from transaction type

---

.circleci/config.yml

.circleci: remove erroneous cd

---

helm-config/values.yaml

helm: correct secret name

---

helm-config/templates/ingress.yaml
helm-config/values.yaml

helm: match values in the old deployment pipeline

---

package-lock.json

run npm audit

---

src/transactions/transaction.controller.ts
src/transactions/transaction.service.ts

adding retrieval of onetimekey status for TRO

---

src/transactions/transaction.service.ts

fixes api call

---

.circleci/config.yml
README.md
docker-compose.ci.yml
docker-compose.yml
package-lock.json
package.json
src/config/env.json
test/cache.behaviors.e2e-spec.ts
test/mock/controller.handler.mock.ts
test/transaction.e2e-spec.ts

update acapy to 0.7.1

---

src/multitenant/dtos/wallet.create.dto.ts
src/multitenant/mulittenant.service.ts
test/multitenant.connections.e2e-spec.ts
test/multitenant.credential.e2e-spec.ts

add option to return token

---

src/transactions/messaging/report.message.handler.ts
src/transactions/messaging/transaction.message.handler.ts
src/transactions/messaging/transaction.message.response.factory.ts
test/transaction.e2e-spec.ts

Fixes basic message sends for multitennant

---

README.md

adding deployment section

---

src/manager/agent.config.ts

Signed-off-by: CamP <caeparra@gmail.com>

add max request size

---

.circleci/config.yml

cicd: upgrade machine to ubuntu20

---

docker-compose.yml
src/app/app.controller.ts
src/app/app.service.ts
src/app/dtos/service.report.dto.ts

Please see https://github.com/kiva/protocol-services-support/pull/2 and uptime statistics feature brief

adding initial support for for uptime statistics
